services:
  SPlayer:
    build:
      context: .
    image: splayer
    container_name: SPlayer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /vol2/1000/音乐:/app/downloads  # 下载路径挂载
      - /vol1/1000/docker/splayer/config:/root/.config/SPlayer
    ports:
      - 25884:25884
    restart: always
    privileged: true
    environment:
      - NETEASE_SERVER_IP=220.197.30.65
      - UNBLOCK_SOURCES=kugou kuwo bilibili
      - ENABLE_FLAC=false
      - ENABLE_HTTPDNS=false
      - BLOCK_ADS=true
      - DISABLE_UPGRADE_CHECK=false
      - DEVELOPMENT=false
      - FOLLOW_SOURCE_ORDER=true
      - JSON_LOG=false
      - NO_CACHE=false
      - SELECT_MAX_BR=true
      - LOG_LEVEL=info
      - SEARCH_ALBUM=true
      - DOWNLOAD_PATH=/app/downloads  # 强制指定下载路径
